// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNhu5jTa7Cn5dblNCJve3JVoVDt71lIso',
    appId: '1:298013861564:web:5d39a8810678c6ff3f92b9',
    messagingSenderId: '298013861564',
    projectId: 'apptask-7e2d7',
    authDomain: 'apptask-7e2d7.firebaseapp.com',
    storageBucket: 'apptask-7e2d7.firebasestorage.app',
    measurementId: 'G-WP72LWM4GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArrg1d76M18A2mWESaoBwtwD31e4Imxv0',
    appId: '1:298013861564:android:3a9d29d4c898a2213f92b9',
    messagingSenderId: '298013861564',
    projectId: 'apptask-7e2d7',
    storageBucket: 'apptask-7e2d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDccOL4sWBNk3BtNlARsA8d__z8avhBRh8',
    appId: '1:298013861564:ios:523af379e1c3010a3f92b9',
    messagingSenderId: '298013861564',
    projectId: 'apptask-7e2d7',
    storageBucket: 'apptask-7e2d7.firebasestorage.app',
    iosBundleId: 'com.ngonzano.fluttertask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDccOL4sWBNk3BtNlARsA8d__z8avhBRh8',
    appId: '1:298013861564:ios:051c847a0030facd3f92b9',
    messagingSenderId: '298013861564',
    projectId: 'apptask-7e2d7',
    storageBucket: 'apptask-7e2d7.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNhu5jTa7Cn5dblNCJve3JVoVDt71lIso',
    appId: '1:298013861564:web:274092bd939525853f92b9',
    messagingSenderId: '298013861564',
    projectId: 'apptask-7e2d7',
    authDomain: 'apptask-7e2d7.firebaseapp.com',
    storageBucket: 'apptask-7e2d7.firebasestorage.app',
    measurementId: 'G-E0PC5MGXMN',
  );
}
